######################## default configuration ####################

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Charis | Jute Bags | Buy high quality jute bags"
theme= "ecom-hugo-theme"
summaryLength = "20"

[params]
logo = "/images/logo.png"
og_image = "images/ogimage.jpg"
description = "Charis Jute bags is a high quality multipurpose Jute bags manufacturers."
keywords = "Jute bags, jute, organic bags, shopping jute bags, jute hand bags, mens hand bags, womens hand bag, fashionable hand bags"
author = "TenSketch"

# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "0124857985320"
email = "info@charisjutebags.com"
location = "Chennai, India"
# copyright
copyright = "| Copyright &copy; 2021 [Charis](https://charisjutebags.com) All Rights Reserved |"
# Snipcart Credentials
snipcartApiKey = "YourAPIkey"
currencySymbol = "Rs. "

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"


[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

  [languages.ae]
    languageName = "Arabic"
    languageCode = "ae"
    weight = 2

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/drift-zoom/drift-basic.min.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/drift-zoom/Drift.min.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  identifier = "Jute bags"
  name = "Jute bags"
  URL = "jute_bags"
  weight = 1

  [[menu.main]]
  identifier = "Women's jute bags"
  name = "Women's jute bags"
  URL = "/categories/women/"
  parent = "Jute bags"
  weight = 1

  [[menu.main]]
  identifier = "Jute gift bags"
  name = "Jute Gift bags"
  URL = "/categories/gift-or-giveaway/"
  parent = "Jute bags"
  weight = 2

  [[menu.main]]
  identifier = "Cotton bags"
  name = "Cotton bags"
  URL = "/categories/shopping/"
  parent = "Jute bags"
  weight = 3

  [[menu.main]]
  identifier = "Household"
  name = "Household"
  URL = "/"
  weight = 2

  [[menu.main]]
  identifier = "Storage baskets"
  name = "Storage baskets"
  URL = "/"
  parent = "Household"
  weight = 1

  [[menu.main]]
  identifier = "Kitchen and Dining room"
  name = "Kitchen and Dining"
  URL = "/"
  parent = "Household"
  weight = 2

  [[menu.main]]
  identifier = "Decoration and Accessories"
  name = "Decoration and Accessories"
  URL = "/"
  parent = "Household"
  weight = 3


  [[menu.main]]
  name = "About us"
  URL = "#"
  weight = 3

