######################## default configuration ####################

baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Charis | Jute Bags | Buy high quality jute bags"
theme= "ecom-hugo-theme"
summaryLength = "20"

[params]
logo = "images/Charis_CT-logo.png"
og_image = "images/ogimage.jpg"
description = "Charis Jute bags is a high quality multipurpose Jute bags manufacturers."
keywords = "Jute bags, jute, organic bags, shopping jute bags, jute hand bags, mens hand bags, womens hand bag, fashionable hand bags"
author = "TenSketch"

# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "0124857985320"
email = "info@charisjutebags.com"
location = "Chennai, India"
# copyright
copyright = "| Copyright &copy; 2021 [Charis](https://charisjutebags.com) All Rights Reserved |"
# Snipcart Credentials
snipcartApiKey = "YourAPIkey"
currencySymbol = "Rs. "

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

  [languages.ae]
    languageName = "Arabic"
    languageCode = "ae"
    weight = 2

############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "About us"
  URL = "about-us"
  weight = 1

  [[menu.main]]
  name = "Jute bags"
  URL = "jute_bags"
  weight = 2

  [[menu.main]]
  name = "Gifts"
  URL = "gifts"
  weight = 3

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4